name: table_calendar
description: Highly customizable, feature-packed calendar widget for Flutter.
version: 3.1.2
author: Aleksander Woźniak <aleksanderwozniak96@gmail.com>
homepage: https://github.com/aleksanderwozniak/table_calendar

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl:
    git:
      url: https://github.com/engineerforce-inc/i18n.git
      ref: da3b47a
      path: pkgs/intl
  simple_gesture_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
